// Per-city flavour: localities, landmarks, signboards, colours, traffic mix, people and dialogue.
// `CITY` is a live binding, so modules that import it see the selected city.

const LAHORE = {
  id: 'lahore',
  name: 'Lahore',
  urdu: 'لاہور',
  tagline: 'Zinda Dilan-e-Lahore',
  seed: 1337,
  localities: [
    'Anarkali', 'Liberty Chowk', 'Ichhra', 'Mozang', 'Saddar', 'Raja Bazaar',
    'Gulberg', 'Model Town', 'Shadman', 'Garhi Shahu', 'Qila Gujjar Singh',
    'Bhati Gate', 'Lohari Gate', 'Data Darbar', 'Mall Road', 'Township',
    'Lakshmi Chowk', 'Nila Gumbad', 'Hall Road', 'Mochi Gate', 'Shah Alami',
    'Faisal Town', 'Johar Town', 'Samanabad', 'Krishan Nagar', 'Baghbanpura',
    'Shalimar', 'Misri Shah', 'Mughalpura', 'Chauburji', 'Bilal Ganj', 'Sanda',
    'Islampura', 'Rang Mahal', 'Kashmiri Bazaar', 'Urdu Bazaar', 'Beadon Road',
    'Regal Chowk', 'Dharampura', 'Walton', 'Cavalry Ground', 'Wahdat Road',
    'Muslim Town', 'Canal View', 'Kalma Chowk', 'Gawalmandi', 'Fortress Stadium',
  ],
  // block (i,j) -> special kind
  layout: {
    '3,3': ['park', 'Minar-e-Pakistan'],
    '1,4': ['mosque', 'Badshahi Masjid'],
    '5,2': ['station', 'CNG Station'],
    '4,5': ['bazaar', 'Anarkali Bazaar'],
    '2,1': ['bazaar', 'Liberty Market'],
    '5,5': ['dhaba', 'Gawalmandi Food Street'],
  },
  mosqueStyle: 'red',
  signs: [
    ['جنرل اسٹور', 'GENERAL STORE'], ['حلوہ پوری', 'HALWA PURI'], ['موبائل شاپ', 'MOBILE ZONE'],
    ['میڈیکل اسٹور', 'MEDICAL STORE'], ['کریانہ اسٹور', 'KARYANA STORE'], ['ٹیلر ماسٹر', 'TAILOR MASTER'],
    ['چائے خانہ', 'CHAI KHANA'], ['بیکری اینڈ سویٹس', 'BAKERS & SWEETS'], ['نان شاپ', 'TANDOOR'],
    ['بریانی سینٹر', 'BIRYANI CENTRE'], ['الہ دین ہیئر کٹنگ', 'HAIR SALOON'], ['بسم اللہ ہوٹل', 'BISMILLAH HOTEL'],
    ['مدینہ کلاتھ ہاؤس', 'CLOTH HOUSE'], ['فوٹو اسٹیٹ', 'PHOTOSTAT'], ['ایزی لوڈ', 'EASYLOAD'],
    ['پان شاپ', 'PAAN SHOP'], ['لاہوری نہاری', 'NIHARI HOUSE'], ['سجی اینڈ کڑاہی', 'KARAHI POINT'],
    ['الیکٹرک اسٹور', 'ELECTRIC STORE'], ['آٹو پارٹس', 'AUTO PARTS'], ['جوس کارنر', 'JUICE CORNER'],
    ['کتاب گھر', 'BOOK DEPOT'], ['ہارڈویئر', 'HARDWARE'], ['شوز سینٹر', 'SHOES CENTRE'],
    ['ڈاکٹر کلینک', 'CLINIC'], ['جیولرز', 'JEWELLERS'], ['دودھ دہی', 'MILK SHOP'],
    ['سموسہ پکوڑا', 'SAMOSA PAKORA'], ['پراپرٹی ایڈوائزر', 'ESTATE AGENT'], ['آپٹیکل', 'OPTICS'],
    ['کمپیوٹر سینٹر', 'COMPUTERS'], ['لسی ہاؤس', 'LASSI HOUSE'],
  ],
  tints: ['#efe9dc', '#e8d9b5', '#dccbb0', '#f2e2c4', '#cfd9c9', '#d9c3b0', '#e6c6b8', '#c9d4dc',
    '#f0e0a8', '#bfcfc0', '#e7d3e0', '#d8b99a', '#f4efe6', '#b9c9d6', '#e3b98f', '#a9c2a4'],
  oldTints: ['#c9a27e', '#b99a7a', '#d2b48c', '#c4a383', '#b58a6a'],
  oldStyles: [2, 2, 3],
  oldChance: 0.6,
  mountains: false,
  bunting: ['#01411c', '#f5f5f5'],
  traffic: [['sedan', 9], ['hatch', 8], ['bike', 13], ['rickshaw', 7], ['van', 3], ['pickup', 3], ['bus', 3], ['truck', 3], ['donkey', 2]],
  people: { female: 0.3, burqa: 0.22, blueBurqa: 0, cap: 0.22, pakol: 0.02, turban: 0.04, waistcoat: 0.12, chadar: 0.05 },
  animals: 10,
  haze: { fog: 1.0, tint: null },
  radio: 'FM 103 · Lahori Beats',
  scale: 'yaman',
  pickup: [
    'Bhai, {d} chalo ge?', 'Assalam-o-Alaikum! {d} jana hai, jaldi karo.',
    'Rickshaw! {d} tak kitne ka? Chalo theek hai.', 'Bhai sahab, {d} le chalo, meter wala scene nahi.',
    'Jaldi {d} pohanchao, class shuru hone wali hai!', 'Beta, {d} jana hai. Aaram se chalana.',
    'Oye rickshaw! {d}! Double paise dunga agar jaldi pohanchaya.', '{d} chalo, wahan ke paye bohat mashoor hain!',
    'Bhai jaan, {d}. Aur haan, gaana thora ooncha kar do.', 'Ammi ne bulaya hai, {d} jaldi!',
  ],
  pay: ['Shukriya bhai, yeh lo.', 'Allah Hafiz, jeete raho!', 'Zabardast! Yeh lo paise.', 'JazakAllah bhai.', 'Lahore Lahore aye! Shukriya.'],
};

const PESHAWAR = {
  id: 'peshawar',
  name: 'Peshawar',
  urdu: 'پشاور',
  tagline: 'City of Flowers',
  seed: 9191,
  localities: [
    'Qissa Khwani', 'Saddar', 'Hayatabad', 'University Road', 'Khyber Bazaar', 'Namak Mandi',
    'Karkhano Market', 'Board Bazaar', 'Ghanta Ghar', 'Kohati Gate', 'Dabgari', 'Chowk Yadgar',
    'Gulbahar', 'Firdous', 'Faqirabad', 'Tehkal', 'Jamrud Road', 'Peshawar Cantt', 'Shoba Bazaar',
    'Andar Shehr', 'Sethi Mohallah', 'Hashtnagri', 'Lahori Gate', 'Kabuli Gate', 'Ramdas Bazaar',
    'Dalgaran', 'Mohallah Jangi', 'Bazaar-e-Kalan', 'Shafi Market', 'Arbab Road', 'Warsak Road',
    'Pajagi Road', 'Charsadda Adda', 'Yakatoot', 'Nothia', 'Gulberg', 'Ring Road', 'Sikandarpura',
    'Kakshal', 'Asia Gate', 'Mohabbat Abad', 'Shah Qabool', 'Bara Gate', 'Khyber Road',
    'Pipal Mandi', 'Chowk Nasir Khan', 'Mochi Lara',
  ],
  layout: {
    '3,3': ['clocktower', 'Ghanta Ghar'],
    '1,1': ['fort', 'Bala Hisar'],
    '4,4': ['mosque', 'Mahabat Khan Masjid'],
    '5,2': ['station', 'CNG Station'],
    '3,4': ['bazaar', 'Qissa Khwani Bazaar'],
    '2,3': ['bazaar', 'Namak Mandi'],
    '5,5': ['dhaba', 'Chapli Kabab Street'],
    '1,5': ['bazaar', 'Karkhano Market'],
  },
  mosqueStyle: 'white',
  signs: [
    ['چپلی کباب', 'CHAPLI KABAB'], ['قہوہ خانہ', 'QEHWA KHANA'], ['پشاوری چپل', 'PESHAWARI CHAPPAL'],
    ['ڈرائی فروٹ', 'DRY FRUIT'], ['کابلی پلاؤ', 'KABULI PULAO'], ['خیبر ہوٹل', 'KHYBER HOTEL'],
    ['نمک منڈی تکہ', 'NAMAK MANDI TIKKA'], ['قالین ہاؤس', 'CARPET HOUSE'], ['پکول ٹوپی ہاؤس', 'PAKOL CAP HOUSE'],
    ['پشاوری آئس کریم', 'ICE CREAM'], ['نان شاپ', 'TANDOOR'], ['موبائل مارکیٹ', 'MOBILE MARKET'],
    ['میڈیکل اسٹور', 'MEDICAL STORE'], ['جنرل اسٹور', 'GENERAL STORE'], ['باڑہ مارکیٹ', 'BARA MARKET'],
    ['کپڑا ہاؤس', 'CLOTH HOUSE'], ['شنواری ریسٹورنٹ', 'SHINWARI'], ['دم پخت', 'DUMPUKHT'],
    ['تاج ٹیلرز', 'TAJ TAILORS'], ['گل بہار جیولرز', 'GULBAHAR JEWELLERS'], ['کتاب گھر', 'BOOK DEPOT'],
    ['آٹو پارٹس', 'AUTO PARTS'], ['ٹرک آرٹ ورکشاپ', 'TRUCK ART'], ['خشک میوہ جات', 'DRY FRUITS'],
    ['ڈاکٹر کلینک', 'CLINIC'], ['ایزی لوڈ', 'EASYLOAD'], ['جوس کارنر', 'JUICE CORNER'],
    ['پان شاپ', 'PAAN SHOP'], ['سجی', 'SAJJI'], ['ہارڈویئر', 'HARDWARE'], ['حلوہ پوری', 'HALWA PURI'],
    ['رباب ہاؤس', 'RABAB HOUSE'],
  ],
  tints: ['#d8c6a8', '#c9b08a', '#e0d2b8', '#d1bfa0', '#e6dcc8', '#c4b49a', '#d6c8ae', '#e2d5bd',
    '#eef0ea', '#dfe6dc', '#cfdcd8', '#e8dcc0', '#b9ccc4', '#e4d0c0', '#f0ead8', '#c8d4dc'],
  oldTints: ['#b88f68', '#a6805c', '#c49a70', '#9c7652', '#b08660'],
  oldStyles: [3, 3, 2],
  oldChance: 0.75,
  mountains: true,
  bunting: ['#01411c', '#f5f5f5'],
  traffic: [['sedan', 6], ['hatch', 5], ['bike', 9], ['rickshaw', 8], ['van', 3], ['pickup', 5], ['bus', 3], ['truck', 6], ['tonga', 5]],
  people: { female: 0.18, burqa: 0.55, blueBurqa: 0.5, cap: 0.08, pakol: 0.35, turban: 0.14, waistcoat: 0.35, chadar: 0.2 },
  animals: 12,
  haze: { fog: 0.8, tint: '#d4c09c' },
  radio: 'FM 101 · Rabab Tappay',
  scale: 'pahari',
  pickup: [
    'Khan sahab, {d} chalo!', 'Wrora, {d} ta zu. Zar sha, zar sha!', 'Salaam, {d} jana hai. Kitna loge?',
    'Chapli kabab khane {d} ja raha hoon, jaldi karo!', 'Lala, {d}. Qehwa thanda ho raha hai!',
    'Bhai {d} le chalo, dukaan kholni hai.', 'Staray mashay! {d} tak chaloge?',
    '{d}! Aur rastay mein Peshawari ice cream bhi le lena.', 'Mama, {d} chalo, Jumma ki namaz se pehle.',
  ],
  pay: ['Manana wrora!', 'Da Khuday pa amaan!', 'Shukriya Khan sahab, yeh lo.', 'Kha, sha! Yeh lo kiraya.', 'Mehrabani lala.'],
};

export const CITIES = { lahore: LAHORE, peshawar: PESHAWAR };
export let CITY = LAHORE;

export function selectCity(id) {
  CITY = CITIES[id] || LAHORE;
  return CITY;
}
